travis/setup_dependencies_common.sh

Don’t show conda progress bars

---

.travis.yml
README.md
test_env.py
travis/setup_dependencies_common.sh

Adding support for build_docs

---

test_env.py

@astrofrog Did you mean to test for the python version only in the tests, or have a built-in test in the package itself in the install scripts?
Fixes #15

Test python version

---

appveyor.yml

This is to test out the fix in https://github.com/numpy/numpy/pull/6702

Fix Numpy dev build on AppVeyor

---

.travis.yml
README.md
appveyor.yml
appveyor/install-miniconda.ps1
test_env.py
travis/setup_dependencies_common.sh

``ci-helpers`` is getting ready for the new astropy stable 1.1 :)

Adding support for astropy lts

---

.travis.yml
README.md
travis/setup_conda_linux.sh
travis/setup_conda_osx.sh
travis/setup_dependencies_common.sh

This is to address the discussion in #25. Closes #25.
ping @cdeil @astrofrog

Turn on bash debugging and print some extra info

---

travis/setup_dependencies_common.sh

As the current setup causes more problems as it solves.

Changing mpl version to be less strict

---

.travis.yml
README.md
test_env.py
travis/setup_dependencies_common.sh

This is to fix #42 (in favour of #41, so closes #41).
@astrofrog - What do you think? Should we introduce an env variable to opt into this, or can this be the behaviour always?

Pinning dependency versions

---

appveyor.yml
travis/setup_dependencies_common.sh

Conda supposed to be lowercase only anyway.

Making sure all conda pendenency package is written lowercase 

---

.travis.yml
travis/setup_dependencies_common.sh

in the pinfile, too. This should have been part of #45.

Making sure all conda pendenency package is written lowercase

---

.travis.yml
README.md
test_env.py
travis/setup_dependencies_common.sh

Fixing corner cases of version pinning

---

README.md
travis/setup_conda_linux.sh

Revert "Travis add mpl backend setup"

---

.travis.yml
travis/setup_dependencies_common.sh

Builds on #56 with fixing the test, so closes #56.

Pin mpl to <=1.5.0

---

README.md
appveyor.yml
appveyor/install-miniconda.ps1

I've just needed such option (as used in travis) for sunpy/sunpy#1629.
I'm not sure whether that's they way and I don't know how I could test this locally...

allow to set channels from the yml file

---

.travis.yml
README.md
travis/setup_dependencies_common.sh

Similarly as with numpy. Only works for travis for now.

Adding support for astropy pre-releases

---

test_env.py

Continuum builds of numpy 1.11 have been released.

Update numpy version to latest stable version

---

README.md
appveyor/install-miniconda.ps1
appveyor/windows_sdk.cmd
travis/setup_conda_linux.sh
travis/setup_conda_osx.sh
travis/setup_dependencies_common.sh

Almost all the links can be accessed securely over https.

Use secure links where possible.

---

appveyor.yml

rather than the temporary 'Previous'

Changing pinned version of VS to VS 2015 Update 2 

---

.travis.yml
appveyor.yml
appveyor/install-miniconda.ps1

This closes #121.
The first commit adds only the test and thus should fail.

Multiple packages in PIP_DEPENDENCIES for appveyor

---

.travis.yml
README.md
travis/setup_conda.sh

Simplify how to call the Travis set-up script

---

.travis.yml
README.md
appveyor.yml
appveyor/install-miniconda.ps1
test_env.py
travis/setup_dependencies_common.sh

I'm not sure how we can test this, apart from creating two fake test channels...

Make channel_priority configurable via environment variable

---

.travis.yml
README.md
appveyor/install-miniconda.ps1
travis/setup_dependencies_common.sh

This is to close #119.
Should not be merged before the related PRs merged to the affiliates.

Removing channels added by default

---

travis/setup_conda_osx.sh

See the error here:
https://travis-ci.org/astropy/ci-helpers/jobs/161719590

Add workaround for Travis issue on MacOS X

---

appveyor/install-miniconda.ps1
travis/setup_conda_linux.sh
travis/setup_conda_osx.sh

Experimenting to see if this fixes https://github.com/astropy/ci-helpers/issues/137

AppVeyor: workaround for issues downloading the Miniconda file

---

appveyor/install-miniconda.ps1
travis/setup_conda_linux.sh
travis/setup_conda_osx.sh

Switch URLs back to https

---

travis/setup_dependencies_common.sh

Uninstall conda version of astropy before installing it with pip

---

travis/setup_dependencies_common.sh

Otherwise we run into issues like this:
https://travis-ci.org/astropy/regions/jobs/174034243
cc @bsipocz

Use --force when uninstalling astropy

---

appveyor/install-miniconda.ps1

As @MSeifert04 says in #143 the original issue has been solved.
(This was a workaround added in #82)

Remove the mkl version pinning in appveyor

---

test_env.py
travis/setup_dependencies_common.sh

We should wait with merging until the conda package is out, but nevertheless it's good to have this PR open now.

Updating astropy stable version to 1.3

---

.travis.yml
travis/setup_dependencies_common.sh

Add flake8 to possible test commands

---

.travis.yml
appveyor.yml
appveyor/install-miniconda.ps1
travis/setup_conda_linux.sh
travis/setup_conda_osx.sh
travis/setup_dependencies_common.sh

This should be a workaroud for #161 until there is a solution for https://github.com/conda/conda/issues/4579
We keep accepting space separated values only.

Preventing conda picking up our CONDA_CHANNELS variable

---

.travis.yml
travis/setup_dependencies_common.sh

When both astropy and numpy is set to stable
(For problems see #166)

Dealing with double stable cases

---

.travis.yml
appveyor/install-miniconda.ps1
test_env.py
travis/setup_dependencies_common.sh

Basically the same logic as for travis in #169.

Appveyor: fall back on pip install when conda install fails

---

.travis.yml
travis/setup_dependencies_common.sh

Looping through conda dependencies when falling back on pip installing them

---

LICENSE.rst
travis/setup_dependencies_common.sh

@astrofrog - Does it look OK to you? The license was copied over from the template.
Also I wonder whether we need the dates? If yes, is this the preferred format, or can it be open ended (2015--)?
Close #177

Adding license

---

travis/setup_dependencies_common.sh

conda channels should be a space separated list. Otherwise channel addition will
fail.

fix comment string

---

.travis.yml
travis/setup_dependencies_common.sh

Adding PYTEST_VERSION and PIP_VERSION

---

travis/setup_dependencies_common.sh

Change ``exit`` to  ``travis_terminate``

---

.travis.yml
travis/setup_dependencies_common.sh

when the required version is not available on conda

pip installing sphinx and mpl for docs

---

appveyor.yml
appveyor/install-miniconda.ps1

We need to check if it works by looking at the log of the build that uses it.

Implement DEBUG environment variable for AppVeyor

---

appveyor.yml
appveyor/install-miniconda.ps1
travis/setup_dependencies_common.sh

Remove this limitation once https://github.com/astropy/astropy/pull/6419 is fully understood and solved.
cc @astrofrog

Limit pytest version to <3.2.0

---

.travis.yml
README.md
appveyor.yml
appveyor/install-miniconda.ps1
conda_environment.yml
travis/setup_dependencies_common.sh

Closes #232.
Let's see if it works!

ENH: Add CONDA_ENVIRONMENT support

---

appveyor/install-miniconda.ps1
test_env.py
travis/setup_dependencies_common.sh

And fix minor bug that appveyor should honour this...

Updating latest stable version of astropy

---

travis/setup_dependencies_common.sh

until https://github.com/sphinx-doc/sphinx/issues/4689 is addressed in a new release

Limiting sphinx not to use 1.7

---

travis/setup_dependencies_common.sh

Fix #282 (specifically just the `KeyError`, not the rest of the failure in `stginga`)

Export PYTHON_VERSION

---

.travis.yml
appveyor/install-miniconda.ps1
travis/setup_conda_linux.sh
travis/setup_conda_osx.sh
travis/setup_dependencies_common.sh

This is just to see if all the tests pass with the latest version - and since it's bugfix release number 10, I'm hoping it has some degree of stability...

Update pinned conda version to 4.5.10

---

appveyor/install-miniconda.ps1
travis/setup_dependencies_common.sh

This should fix the case when the variable exists but empty (e.g. https://travis-ci.org/desihub/desisim/jobs/425856869)

Never pass CONDA_CHANNELS to conda

---

README.md
travis/setup_conda_linux.sh
travis/setup_conda_osx.sh
travis/setup_dependencies_common.sh

This PR allows the miniconda version to be selected programmatically, and defaults to the currently (pinned) version.

Miniconda version

---

.travis.yml
test_env.py
travis/setup_dependencies_common.sh

Adding support for testing dev version of mpl

---

.travis.yml
appveyor/install-miniconda.ps1
travis/setup_dependencies_common.sh

even when it's not available in conda

Upgrade pip to the latest version

---

README.md
utils/import_submodules.py

This is the infrastructure for @eteq's feature request of adding import only travis tests https://github.com/astropy/astropy/issues/7939 based on @astrofrog's comment.

Adding utility function to test importing all submodules from packages

---

.travis.yml
travis/setup_dependencies_common.sh

Do not terminate for stable==lts astropy any more

---

appveyor.yml
appveyor/install-miniconda.ps1

This is needed to make the appveyor tests pass for https://github.com/astropy/astropy/pull/8173
~~WIP: first wants to make sure the tests is failing...~~

Adding PYTEST_VERSION for appveyor

---

travis/setup_dependencies_common.sh

As suggested by @rgommers (thank you! 🙏 ) over at https://github.com/numpy/numpy/pull/12610#issuecomment-451721733 
I will open an experimental PR over as Astropy to use this branch and see what happens. 🤞 
Fix astropy/astropy#8318

MNT: Use C99 to compile numpy-dev

---

appveyor/install-miniconda.ps1
travis/setup_conda_linux.sh
travis/setup_conda_osx.sh
travis/setup_dependencies_common.sh

Bump default miniconda version

---

travis/setup_dependencies_common.sh

Since many sphinx versions have been released since 1.7.1

Reverting #287

---

.travis.yml
appveyor/install-miniconda.ps1

We do this on travis, but apparently not yet on appveyor (and it made the builds stall for regions)

Set MPLBACKEND to be Agg by default on appveyor, too

---

appveyor.yml
appveyor/install-miniconda.ps1

to fix https://github.com/astropy/ci-helpers/issues/398

Fixing syntax for PS env variables

---

travis/setup_conda.sh

Ensure PEP 8 runs for [docs only] directive

---

travis/setup_dependencies_common.sh

Leave nomkl alone if numpy is not defined by NUMPY_VERSION

---

travis/setup_conda.sh

@jhunkeler pointed out my sins to me in #407 .
I'll find a way to test this before merge...
Edit: Fix the bug part of #417, keeping that issue open until the enhancement part is investigated.

BUG: Fix broken [docs only] directive

---

README.md
appveyor.yml
appveyor/install-miniconda.ps1
test_env.py

Built on #415, this is my attempt at getting rid of all of the extra PATH and activation hackery that was needed. Probably won't work, but let's see what happens.

Test more modern appveyor setup

---

.travis.yml
travis/setup_dependencies_common.sh

Maybe the third time will be the winning one.

Limit even more coverage 

---

tox/run_tox.sh

Some further tweaks needed for astropy core.

Allow python interpreter to be overriden and make sure pip and setuptools are recent

---

.travis.yml

I don't question `conda` resolver's logic. Just trying to fix what I see in the log.

TST: Fix build_sphinx job

---

.travis.yml
appveyor.yml
travis/setup_dependencies_common.sh

TST: Fix CI failures

---

.travis.yml
README.md
travis/setup_dependencies_common.sh

This is an attempt to help address #456

Add a way to opt in to using mamba for install commands
