astropy/ci-helpers

- .gitignore
- .travis.yml
- appveyor.yml
- appveyor/install-miniconda.ps1
- test_env.py
As discussed on gitter, adding a python script to run in the appveyor and travis tests has several benefits. 
The most obvious that it circumvent the parsing issues of the ``appveyor.yml`` file, so not only one liners can be run.
It also enables us to to a more thorough testing, and easy extension in the future.
Fixes #10
> Adding test_env script

- .travis.yml
- README.md
- travis/setup_dependencies_common.sh
Added the 'stable' option to NUMPY_VERSION in the travis scripts, and minor changes in README about that ``install`` is the suggested place for including ``ci-helpers`` (rather than ``before-install``).
> Travis adding stable numpy

- appveyor/windows_sdk.cmd
This helps address astropy/photutils#294 by properly configuring appveyor for python 3.5. The change is necessary because the default compiler for python on Windows changed in python 3.5.
> Update appveyor configuration for python 3.5

- appveyor/install-miniconda.ps1
Fixed a number of bugs assuming that miniconda will be installed to c:\conda (hard coded) as opposed to the path specified by $env:PYTHON
> Fix instances of hard-coded c:\conda

- appveyor/install-miniconda.ps1
pip installs should be preceded by the `%CMD_IN_ENV%` invokation to set up the Windows SDK environment when appropriate, since pip install will often (not always, depending on wheel availability) result in a build from source, in which case we presumably want to build for the same platform as the package that we're testing.
> Set up Windows SDK when calling pip install

- travis/setup_dependencies_common.sh
As discussed in #27 it has advantages to fail the build when something goes wrong with the installs (rather than let the test run and produce random failures that are mostly unrelated to the given package).
> Adding 'set -e' to the install script

- .travis.yml
- appveyor.yml
- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
In the following build:
https://travis-ci.org/glue-viz/glue/jobs/100871829
Numpy dev is installed, followed by conda packages, which includes Numpy, which takes precedence, so Numpy dev is ignored.
> NUMPY_VERSION=dev not working if installing other conda packages that depend on Numpy

- README.md
- travis/setup_dependencies_common.sh
as it's really only for debugging, and the warnings it generates messes up the sphinx builds warning catching system.
> Removing conda info command from the build script

- travis/setup_dependencies_common.sh
`travis-ci` sphinx builds will fail with `matplotlib 1.5.1` because of a warning about `fc-list`.  This PR can be reverted once https://github.com/matplotlib/matplotlib/issues/5836 is fixed.
> Fix matplotlib version to 1.5.0 for travis-ci sphinx builds

- .travis.yml
- README.md
- test_env.py
- travis/setup_dependencies_common.sh
In Glue, I was passing flags to conda using e.g.
```
CONDA_DEPENDENCIES='numpy scipy --no-deps'
```
this is now broken BUT I think that's fine, since this isn't really a proper way to do it. So I would suggest we add a new variable ``$CONDA_FLAGS`` to deal with passing any flags such as this.
> Have a way to provide options to conda

- README.md
- travis/setup_conda_linux.sh
This is to address and close #26.
@astrofrog - do we need to test this somehow?
> Travis add mpl backend setup

- .travis.yml
- README.md
- travis/setup_dependencies_common.sh
- we should handle alphanumeric package names when pinning the versions
- fixing #52 by adding ``*`` to the end of all lines with ``==`` in the pin file
- addressing #50 with building the ``-q`` conda flag into the $DEBUG variable
> Various enhanchements for the travis builds

- .travis.yml
- README.md
- travis/setup_dependencies_common.sh
As most of the affiliated packages have their conda version there already.
> Adding the astropy channel to the default value of CONDA_CHANNELS 

- .travis.yml
- travis/setup_dependencies_common.sh
I think the current way of hard-wiring the version to <=1.5.0 for mpl for all the docs builds isn't the right way to do it. 
E.g. it will potentially cause failures for packages that require a version of 1.4.x (as it's overrides everything, and thus 1.5.0 will be installed for those packages, too even though 1.4.x will be perfectly fine for the docs build).
Also as a somewhat separate fix, this PR makes sure that SPHINX_VERSION and MATPLOTLIB_VERSION are taken into account for the docs builds, even when they are not listed as a conda dependency (thus their versions are not pinned).
@astrofrog - Could you please review it?
> Updating the pinning of matplotlib version for docs builds

- .travis.yml
- travis/setup_dependencies_common.sh
Fixing the case when mpl is listed as dependency but without version number (thus is listed in the pinfile, but without any restriction).
> Fixing one more corner case for mpl pinning

- .travis.yml
- appveyor.yml
- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
While it was correct to move the installation of dev versions of packages after ``CONDA_DEPENDENCIES``, I think they should be installed before ``PIP_DEPENDENCIES``, otherwise pip will waste time installing e.g. a stable version of astropy, only to then replace it later with the dev version. With pip, there is no risk that pip will override the dev version though (unlike conda)
> PIP_DEPENDENCIES should be installed after dev versions

- .travis.yml
- test_env.py
- travis/setup_dependencies_common.sh
To reproduce (on Linux):
```
conda create -n test python=2.7 scipy cython
source activate test
pip install https://github.com/numpy/numpy/archive/master.zip
```
then run:
```python
import numpy as np
from scipy.linalg import inv
x = np.random.random((3,3))
inv(x)
```
The error is:
```
Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.
```
This repo shows a minimal failing example with ci-helpers:
https://github.com/astrofrog/debug-mkl
https://travis-ci.org/astrofrog/debug-mkl/builds/108036541
There are two possible solutions:
* As a workaround, pin Scipy to 0.15 to prevent 0.17 from getting installed
* The proper solution is probably to git clone the Numpy repository, and edit the ``site.cfg`` file to point to the conda MKL library, and make sure we use that
> Issue with Numpy dev now that the conda Scipy/Numpy packages are compiled against MKL

- .travis.yml
- README.md
- test_env.py
- travis/setup_dependencies_common.sh
If a pre release is available install it and run the tests, otherwise abort the build (which would result a pass on travis).
It definitely works when no pre release is available, but I'm not 100% sure it would pick up the pre release as the strings may need some adjustments.  Now it's assumed "pre" is in the name of the pre-release.
@mhvk: is this what you've thought of?
> Handling of pre-releases of numpy

- appveyor.yml
Removing unnecessary build, and adding the CONDA_CHANNELS testing into an already existing build to save up a bit of build time.
> Simplifying appveyor matrix

- README.md
- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
Maybe one or both of the others can be removed, as well?
> Adding the openastronomy conda channel to the default channels

- .travis.yml
- travis/setup_dependencies_common.sh
With the new 1.4 sphinx we run into 2 WARNINGS. This affects every package that uses astropy-helpers, thus I think it's sensible to add a requirement for the sphinx version to be ``<1.4`` here and not at the package level.
For packages that run the sphinx build without the ``-w`` option, and thus are insensitive of these warnings, there is an option to use the ``SPHINX_VERSION`` variable to override this limitation.
We can remove this once the issue is address in the helpers.
The warnings are:
```
WARNING: while setting up extension astropy_helpers.sphinx.ext.autodoc_enhancements: directive 'autoattribute' is already registered, it will be overridden
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.
```
@astrofrog - What do you think?
> Temporary fixing of sphinx version to be <1.4

- appveyor/install-miniconda.ps1
as mkl 11.3.3 has some issues with scipy (11.3.1 worked fine)
See https://github.com/astropy/astropy/pull/4907 for the start of the discussion.
[Edit]:  - There is no ``nomkl``, thus I went with hardwiring the mkl version to 11.3.1 that worked before. Everyone else is seeing this issue with scipy, and I believe this is the official conda issue for it is https://github.com/ContinuumIO/anaconda-issues/issues/792. I'll remove the version limit once it's solved upstream.
> Fixing mkl version to 11.3.1 for appveyor conda installs

- test_env.py
If we are on Travis or AppVeyor, we should check if we are running the tests in the ci-helpers repository, or whether for example someone else is running 'py.test' without arguments after having cloned ci-helpers (in which case we shouldn’t run the ci-helpers tests).
> Make sure other projects don't run ci-helpers tests

- appveyor/install-miniconda.ps1
This closes #85
@astrofrog - Not sure that we can test it, what do you think?
(I'll remove the [skip ci] during rebase, once your PR is in)
> Using latest miniconda for appveyor when no version is given 

- .travis.yml
- README.md
- travis/setup_dependencies_common.sh
This is to close #94.
@astrofrog - I think we should have the pep8 option around until it is pip installable, however I think it should be removed from the readme.
> Adding support for pycodestyle as the renaming of pep8

- README.md
- appveyor/install-miniconda.ps1
- test_env.py
- travis/setup_dependencies_common.sh
This is a workaround for currently failing tests in astropy (e.g. https://github.com/astropy/astropy/pull/5094), a place for discussion for long term solution is in #98
> Remove astropy-ci-extras from the default conda channels

- README.md
- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
as older numpy builds are failing without the astropy builds hosted in it. See discussion in #97 and #98 and on gitter.
We need to come up with a more roboust solution in the long term.
> Adding back astropy-ci-extras

- appveyor/install-miniconda.ps1
- test_env.py
- travis/setup_dependencies_common.sh
This is to work around the recent conda issues when a very old astropy version was picked up when asked for "stable". We make sure that the installed version is from the latest feature release.
In most cases we don't need to force it to be the latest bugfix release, and if a package needs that bugfix they should explicitly state that version number in their travis file rather than use stable.
This is for #100 #98
> Making "stable" version be the latest feature release

- .travis.yml
- test_env.py
- travis/setup_dependencies_common.sh
**Do not merge until there is a new helpers release, as without https://github.com/astropy/astropy-helpers/pull/223 still brakes the py3 builds.**
It seems that there are (two ways)[https://github.com/matplotlib/matplotlib/issues/5836#issuecomment-212052820] to fix the issue we had with the mpl font caching (e.g. #56). 
The first solution is to import mpl before running the tests (sphinx build), the second is to enable caching. 
I think the first one can be sensibly done here in ci-helpers, while the second requires each package to edit their ``.travis.yml``.
> Fixing mpl font caching issue with the suggested workaround

- appveyor.yml
as current one gives internal compiler error for astropy dev
related issues:
https://github.com/astropy/astropy/issues/5137
https://github.com/appveyor/ci/issues/890
> Using previous VS in appveyor

- travis/setup_dependencies_common.sh
Someone (@cdeil if I remember correctly) pointed out this bug, but I can't find the original issue now. It slipped through as it worked with bash on osx, but apparently not for linux. I don't see an obvious way to test it though.
> Fixing bug in stable version workaround

- .travis.yml
- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
Obscure bugs came up again in conda (see https://github.com/conda/conda/issues/2897), this time between v4.1.3 and v4.1.4 so we decided to pin the version and only upgrade when we have resources to test the behaviours of a new release.
> Pinning conda version to 4.1.3

- appveyor/install-miniconda.ps1
as the upstream issue seems to be solved.
cc @astrofrog: What do you say, can we remove this now?
(original PR was #93 to address #92)
> Removing temporary version pinning of vs2015_runtime

- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
The conda channel ``openastronomy`` has builds copied over from ``astropy``, so actually it's better to have to pick those packages from the original astropy channel...
> Changing order of conda channels, so astrpy is overtaking openastronomy

- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
To avoid picking up packages from e.g conda-forge.
E.g.:
https://travis-ci.org/bsipocz/sunpy/jobs/148693645#L495 vs. exact same build with different channel order
https://travis-ci.org/bsipocz/sunpy/jobs/148693840#L487
> Adding defaults channel last to have higher priority

- travis/setup_dependencies_common.sh
Apparently the version upgrade is not working for this workaround. The error is this (from this [travis build](https://travis-ci.org/astropy/astroquery/jobs/150688336#L517):
```
The following packages will be downloaded:
package                    |            build
---------------------------|-----------------
astropy-1.0.1              |       np18py33_0         7.6 MB  astropy-ci-extras
The following NEW packages will be INSTALLED:
astropy: 1.0.1-np18py33_0 astropy-ci-extras
Fetching package metadata ...........
Solving package specifications: ..........
#
beautiful-soup            4.3.2                    py33_0  
html5lib                  0.999                    py33_0  
matplotlib                1.4.0                np18py33_0  
numpy                     1.8.2 …
```
> Adding --ignore-installed to the stable astropy version upgrade

- travis/setup_dependencies_common.sh
Unfixed `coverage` version to use latest one (currently 4.2 from `conda`).
This is to possibly fix the timing problem in astropy/astropy#4826.
c/c @mhvk @MSeifert04
> Unfixed coverage version to use latest one

- travis/setup_dependencies_common.sh
This is an attempt to address #123. 
Not sure how it can be tested, but e.g. in the prerelease travis test, scipy now shouldn't be installed even though it's listed in CONDA_DEPENDENCIES.
~~If this works, I'll add more commits to deal with the astropy step.~~
> Keeping order of installs

- test_env.py
Pytest 3.0 no longer allows pytest.skip to be called directly - see http://doc.pytest.org/en/latest/skipping.html#imperative-xfail-from-within-a-test-or-setup-function
> Fix compatibility with pytest 3.0

- travis/setup_dependencies_common.sh
as 1.4 supposed to work with astropy-helpers 1.2 and above. The workaround was introduces in #78.
https://github.com/astropy/astropy/pull/5567
> Removing the workaround of setting default sphinx version

- travis/setup_dependencies_common.sh
until astropy-helpers 1.3 is out with the fix from https://github.com/astropy/astropy-helpers/pull/275
> Adding back sphinx version pinning for <1.5

- README.md
- travis/setup_dependencies_common.sh
to control builds to run only for certain TRAVIS_EVENT_TYPEs, e.g. don't run for pull requests but only for cron jobs, or pushes.
This would solve our long lived remote testing dilemma for astroquery, and possibly will be valuable for other affiliate packages to run more (or even less) detailed testing when cron scheduled.
I'm adding tests and docs soon, but first asking @astrofrog whether he thinks this is the right way to go.
> Adding EVENT_TYPE variable 

- travis/setup_dependencies_common.sh
This is to remove the version pinning (added in #147) since astropy-helpers 1.3 is out.
> Removing sphinx version pinning (revoke #147)

- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
@astrofrog - I would rather do this separately than the python 3.6. If this works, we can merge this asap and rebase the other PR that still waits for the packages to be available.
> Updating conda version from 4.1.3 to 4.3.4

- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
Current conda latest raises a KeyError (see https://github.com/conda/conda/issues/4324) in one of the typical builds in the affiliates matrix, thus we need to pin to the last non failing version which seems to be 4.1.12. (While 4.2.x may fixed this issue, it has other unrelated errors related to downloads at least up until 4.2.15).
> Pinning conda to 4.1.12

- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
The error we got with conda 4.3.4 in #153 got fixed for 4.3.6. A test run with package helpers passes with all green, so this should be probably OK to go in. (Another test with astropy core is still running, but I'll be able to see the results by the time the tests for this PR finish.)
> Unpinning conda version to the latest release 4.3.6

- travis/setup_dependencies_common.sh
NOTE: this needs conda >=v4.2 so not yet suitable for merging.
This PR adds ``conda config --show`` to be run before the install process starts when in DEBUG mode. This should help with the recent warnings, e.g. here: https://travis-ci.org/astropy/package-template/jobs/192393463#L467
>  Show conda config in DEBUG mode

- travis/setup_dependencies_common.sh
This fixes crashing tests (e.g. see photutils or pydl) and closes #152.
At the moment there is no prerelease version, so difficult to test, but the concept was tested in [0] for photutils . Without this fix the test run usually halted and in ``test_core.py``, see [1], but now it passes and runs everything.
[0] https://travis-ci.org/bsipocz/photutils/jobs/193025698
[1] https://travis-ci.org/astropy/photutils/jobs/190715568
> Using nomkl for numpy prereleases

- appveyor/install-miniconda.ps1
This should close #159 and close astropy/astropy#5776. The `Miniconda-*` files were the same as `Miniconda2-*`, but the windows versions disappeared recently. This should fix the failing appveyor builds for astropy.
> Changing Miniconda to explicit Miniconda3

- appveyor/install-miniconda.ps1
This is ultimately to fix #87.
If the solution in #168  is favorable, we may want to try that for appveyor ,too (when conda install doesn't work, fall back to pip). However the exiting still need to be fixed in either case.
(I need to set up appveyor on my fork, but don't have much time atm, so letting this loose on a PR instead).
> Failing job is the installing unsuccessful

- .travis.yml
- test_env.py
- travis/setup_dependencies_common.sh
This PR fixes a few minor issues.
1) tests should run on forks rather than being skipped (https://travis-ci.org/bsipocz/ci-helpers/jobs/210285831#L842)
2) coverage, or in fact any extra script should run only after success from the main test script, otherwise failures become successes (see #175)
3) openjpeg is not a python package, do not try to import it (dealt with in the 3rd commit that will be pushed after the PR is opened to test whether the fix for the 2nd point is working and the build indeed fail)
4) should also fix the issue with partial matching of package names and including/excluding them from the pin file (see https://github.com/astropy/ci-helpers/pull/174#issuecomment-286129493 and above).
> Tests should run on forks, and other minor fixes

- travis/setup_conda.sh
- travis/setup_conda_linux.sh
- travis/setup_conda_osx.sh
This is our workaround until https://github.com/travis-ci/travis-ci/issues/5032 is implemented by travis-ci...
> Adding check for travis skip in commit message

- .travis.yml
- travis/setup_dependencies_common.sh
This is a workaround until https://github.com/sphinx-gallery/sphinx-gallery/issues/241 is addressed. 
The issue was first seen in https://github.com/sunpy/sunpy/pull/2103, but will bite astropy too once the sphinx version is update on the defaults channel (sunpy uses conda-forge, thus they run into it sooner).
> Limit sphinx version when sphinx-gallery is used

- .travis.yml
- travis/setup_dependencies_common.sh
The sphinx 1.6.1 incompatibility is not only affects ``sphinx-gallery`` but ``sphinx-automodapi`` as well, astropy-helpers v2.0 will have the fix included.
> Always limit sphinx version until astropy-helpers 2.0 is out

- .travis.yml
- travis/setup_dependencies_common.sh
Astropy 1.0.x (and thus everything that uses LTS astropy) on python3.5 requires pytest 2.7.3 and that is not available on either the default or conda-forge channels, so we built it on astropy-ci-extras.
> Using astropy-ci-extras channel for pytest install

- travis/setup_dependencies_common.sh
Currently the packages that are installed with pip are not removed from the pin file when a version is also present. Simple grepping is not sufficient as other packages may have partial matches but we don't want to remove those (e.g. sphinx vs sphinx-gallery)
> Properly checking package name to be remove from conda pin file

- .travis.yml
- travis/setup_dependencies_common.sh
We shouldn't install every dependency that is listed in the pinfile when installing default dependencies (e.g mpl and sphinx for the docs).
This PR also deals with some bugs that caused failing builds when only one package was listed as dependency and it failed to install. Hopefully this will provide a solution for some of the failing builds in https://github.com/hipspy/hips/issues/6
> Fixing some issues with the pip install fallbacks

- .travis.yml
- README.md
- travis/setup_conda.sh
- travis/setup_dependencies_common.sh
Minor clean up of [travis skip], and addition of two new custom tags to the top level script.
This address all ideas in and thus close #188
> Adding [docs only] and [build docs] custom tags

- appveyor/install-miniconda.ps1
- test_env.py
- travis/setup_conda.sh
- travis/setup_conda_linux.sh
- travis/setup_conda_osx.sh
- travis/setup_dependencies_common.sh
In addition to the version update this PR also includes a minor cleanup in the travis scripts to remove code repetitions. As well as adding extra printouts to help debugging. Ideally these should have gone into  separate PR, but now merged into one to save on CI time.
> Numpy stable version updated to 1.13

- travis/setup_conda.sh
To get the latest commit message as apparently TRAVIS_COMMIT_MESSAGE behaves differently for commits depending whether they are in a PR or pushed directly.
This should fix the issue we see in https://github.com/astropy/astropy/pull/6173#issuecomment-307513838
> Using git rather than TRAVIS_COMMIT_MESSAGE

- travis/setup_conda.sh
As travis does merge commits, we need to make sure to dig up the real commit message that is associated with the latest commit in a feature branch of a PR.
> Making sure to use the real commit message

- .travis.yml
- travis/setup_dependencies_common.sh
> Disabling channel priority for pytest install

- .travis.yml
- README.md
- travis/setup_dependencies_common.sh
If "--cov" is found in the `SETUP_CMD` variable install pytest-cov module from
conda.
fixes: #214
> auto install pytest-cov

- .travis.yml
- README.md
- travis/setup_dependencies_common.sh
fixes #213 
A new pytest-xdist version  has been released with the new option. This is now checking for the `numprocesses` flag and installing pytest-xdist. Unfortunately this will only work with pytest-xdist>1.18.0 so when a person is pinning a lower version it will fails. But I'm not sure how much of a problem that is in practice since pinning will cause pytest-xdist to be installed anyway.
> install pytest-xdist when --numprocesses is detected

- travis/setup_dependencies_common.sh
I think it makes sense to not duplicate testing efforts when LTS astropy becomes the latest stable version without the need to manually weed out those jobs from the travis matrices (even though cancelling the builds this way means that half of the installation already happened). It may be possible to do the check a bit further up though in ``setup_conda.py``, but that may mess up things for repos that are still using the OS dependent version of the scripts.
Can't test now without messing up everything with changing the version.
cc @astrofrog
> Skip LTS testing when LTS==stable

- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
I've tested this on travis for astropy and photutils and seems to be working. However we should hold off merging a bit to get a feedback on https://github.com/conda/conda/issues/5774 where I run into issues with ``conda install conda`` for a few buillds. 
However they're working now after a restart.
> Updating conda version to the latest release, 4.3.21

- .travis.yml
- README.md
- appveyor.yml
- appveyor/install-miniconda.ps1
- test_env.py
- travis/setup_dependencies_common.sh
This partially deals with #220. If this works, a generalization can be worked on. The only bottleneck is that the version number for the stable releases are hard-wired. If we want to generalize the understanding of "stable" and "dev" for arbitrarily packages, then we need another, more robust solution (e.g. checking pypi for the latest version, but that possibly opens up whole can of worms).
cc @Cadair @nabobalis
> Custom version tags for sunpy

- .travis.yml
- travis/setup_dependencies_common.sh
A support for newer versions are released in astropy-helpers 2.0, a couple of months ago. 
If you use sphinx-gallery, it's best to require at least 0.1.11 (that was released in May, and contains a fix for the same sphinx 1.6+ issue).
> Removing sphinx version limitation of <1.6

- README.md
Recommend using shallow clones in the README ( cf. https://github.com/astropy/ci-helpers/issues/229 ).
The difference is a 20k download size as compared to 340k for the full git history. Also reduced the run time of this step from 1s to 0.5s on my laptop...
> DOC recommend using shallow clones in the README

- travis/setup_conda_linux.sh
For some packages (Mayavi, vispy) having GLX is important. This is an adapted version of the line I've been using successfully to test CIs while using these packages. It should otherwise be backward compatible with what was being done before.
> ENH: Add GLX extensions and bigger screen

- .travis.yml
- README.md
- appveyor.yml
- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
This is to close #227 by adding a new env variable ``PIP_FALLBACK``. By default this is True, but no pip install fallback will happen if it's set to False.
The pr also contains the comment discussed in #239, thus close #239.
> Make pip install fallback optional

- travis/setup_conda.sh
@astrofrog - are you OK with this change? In #245 @MSeifert04 argued that the overhead is not that big from the point the job gets terminated to actually run the style checkers.
Close #245
> Allowing the stylecheckers to run for docs_only builds

- README.md
- travis/setup_dependencies_common.sh
To get a bit of self consistency.
@kain88-de - Does it look OK to you? (asking as you were added the ``--cov`` trigger for the pytest-cov install)
> coveralls should be installed the same way for --cov as for --coverage

- README.md
- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
We need to update to this version as the infra at the default channel changes with it.
See: https://github.com/conda/conda/issues/6069#issuecomment-333938078
Before merging we need to make sure this will work with at least astropy core and e.g. photutils/astroquery.
https://travis-ci.org/bsipocz/astropy/builds/282870686
https://travis-ci.org/bsipocz/photutils/builds/282871701
https://travis-ci.org/bsipocz/astroquery/builds/282870888
> Updating conda version to latest version 4.3.27

- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
currently that is only astropy dev, the case for stable will also needs the update once 3.0 is out. 
Given that ``pytest-astropy`` is a pseudo package, we can't pip install it with ``--no-deps``, so we absolutely need to make sure it doesn't bring in any upgrade to dependencies already installed with conda, or where we fixed the version number previously. One way around this problem can be to start packaging it for conda.
> installing pytest-astropy for astropy 3.0+ testing

- test_env.py
- travis/setup_dependencies_common.sh
https://github.com/astropy/astropy/pull/6419 has been resolved and there is a mark that the else should be removed again.
I saw that when I now noticed that ci-helper don't install the latest version of pytest.
> remove else clause of resolved PR 6419

- travis/setup_dependencies_common.sh
as a workaround while astropy stable is <2.0.3
(an alternative would be to revert the revert of pinning pytest to <3.2, #257, this may be better as affects only the packages that rely on the astropy testing framework)
> Uninstall hypothesis 

- travis/setup_conda_osx.sh
The suggested workaround has changed in the meantime, so hopefully this will solve the issue we see with the `astropy-helpers` builds (e.g. https://travis-ci.org/astropy/astropy-helpers/jobs/322810349#L1581)
> Update workaround for travis bug

- travis/setup_conda_osx.sh
The issue was a bit tricky, and while the final error looked identical to the previous one, the real issue is actually with the missing signatures.
> One more tweak to the osx builds

- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
We need to update to this version as some stsci packages have some weird conda issues that are solved with conda 4.3.31+
Before merging we need to make sure this will work with at least astropy core and e.g. photutils/astroquery.
https://travis-ci.org/bsipocz/astropy/builds/342439970
https://travis-ci.org/bsipocz/photutils/builds/342441453
> Updating pinned conda version to the latest 4.3.34

- .travis.yml
- appveyor.yml
- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
This is to close #254 
~Currently includes #273, too, needs to be rebased once that PR is merged.~ The conda update PRs stay separate as they are not as critical as this one.
> Conda install pytest-astropy for stable and dev

- appveyor/install-miniconda.ps1
- test_env.py
- travis/setup_dependencies_common.sh
This should fix the python3.4 failures we see with the recent astropy-helpers update PRs.
> Do not install pytest-astropy for the astropy 2.0.x series

- .travis.yml
- travis/setup_dependencies_common.sh
This was suggested by the Anaconda people as a temporarily fix for the segfaulting mpl in docs builds.
> Pinning sip version temporarily

- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
This is still an ugly workaround, but will do the job for now. Should be removed once maplotlib stops segfaulting when installed from the default channel
> Pin sip when matplotlib is a dependency

- .travis.yml
This is an attempt to speed up the build. I don't think we actually need the apt packages?
> Don't install any packages with apt on Travis

- appveyor.yml
- appveyor/install-miniconda.ps1
In cases where PIP_FALLBACK is False, we shouldn't capture the output from the commands (in my case this makes it harder to debug issues). The diff is simpler if you ignore whitespace changes.
> Simplify code when PIP_FALLBACK is False

- appveyor/install-miniconda.ps1
Fixes #323
**Changes**
- Added `PackagesNotFoundError` to the strings triggering a pip fallback in `appveyor/install-miniconda.ps1`
> Added PackagesNotFoundError to pip fallback triggers

- README.md
- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
Fixes #325
**Changes**
- Travis:
- Added the environment variables `RETRY_ERRORS` (errors to search for), `RETRY_MAX` (maximum number of retries), and `RETRY_DELAY` (number of seconds to wait before retrying)
- AppVeyor:
- The corresponding variables are `$env:RETRY_ERRORS`, `$env:RETRY_MAX`, and `$env:RETRY_DELAY`
- Travis and Appveyor:
- If not set from outside of the corresponding scripts, the new variables are initialized as
- `RETRY_ERRORS="CondaHTTPError"`
- `RETRY_MAX=3`
- `RETRY_DELAY=2`
- All calls to `conda install` or `conda create` (and the like) are now wrapped by a function `retry_on_known_error()` that handles automatic re-execution of the wrapped commands if they fail due to any of the errors in `RETRY_ERRORS`. The function `retry_on_known_error()` does *not* interfere …
> Automatically retry conda calls on CondaHTTPError

- .travis.yml
- test_env.py
- travis/setup_dependencies_common.sh
This is to deal with cases when the version number is defined with a relation rather than equality
> pip fallback install to honour non exact version number

- .travis.yml
- travis/setup_dependencies_common.sh
This is a hopefully working approach for #338 that actually isn't working.
> pip fallback install should really honour non exact version number

- travis/setup_dependencies_common.sh
pip is more strict than conda with version matchings and requires one to say `0.18.*` instead of just `0.18*`
> Make version matching pip compatible

- .travis.yml
- travis/setup_dependencies_common.sh
apparently all but pytest versions got handled in https://github.com/astropy/ci-helpers/pull/341
> Making sure pytest version is correctly handled by pip

- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
This undoes https://github.com/astropy/ci-helpers/pull/299 - I *think* it's safe to do this now as I think conda packages for PyQt5 are now pinned against more specific sip versions. The pinning is actually causing issues with some packages (when trying to install glue and matplotlib for example).
(Note: In future it would be good to keep a note of the full details of the environments that e.g. segfaulted so we can verify that new conda packages are indeed available)
> No longer pin sip

- README.md
- travis/setup_dependencies_common.sh
We started to see mpl related segfaults all over different packages (at least astroquery and photutils). This should provide a central fix for all those, and if needed the backend can be overwritten in the individual repos.
> Adding MPLBACKEND=Agg as default

- travis/setup_dependencies_common.sh
This appears to be necessary for Windows, but it should be fine for all other platforms as well.
> Use python -m pip instead of pip directly

- travis/setup_dependencies_common.sh
Closes #363 
As discussed in the related issue, setting the errexit flag in bash with `set -e` combined with ci-helpers requiring the use of `source` means that this flag is set for the rest of the travis job. In travis this causes undesired results when a user's script fails and ends up exiting the entire travis process. This leads to difficult debugging where travis doesn't even include the output for the failing command (flushed log issues maybe) and the job fails.
> Turn errexit off before exiting commons script

- README.md
At the Astropy Coordination Meeting 2018, it was agreed that Gitter usage should be retired for the Astropy Project, if I remember correctly.
Accidentally fix #310
> DOC: Remove gitter badge

- appveyor.yml
As suggested by https://github.com/astropy/ci-helpers/issues/369#issuecomment-451783968 . Fix #369
> Remove outdated Appveyor OS image directive

- travis/setup_dependencies_common.sh
Follow up of #368. This only sets `CFLAGS` in a numpy-dev job if it is not already set. Otherwise, it would overwrite calling package's setting. If the calling package sets its own `CFLAGS`, then it is on them to set it properly for a numpy-dev job themselves.
p.s. Please double check the BASH syntax. Thanks!
> MNT: Only set CFLAGS if not already set

- README.md
- travis/setup_dependencies_common.sh
Since some packages are now using codecov, it makes sense to provide it here
> Install codecov in addition to coveralls

- README.md
- travis/setup_conda_osx.sh
Set default OSX deployment target version to 10.9 since this is required for compiling C++ code with llvm/clang when `-stdlib=libc++` is specified.
This is accomplished with the environment variable `MACOSX_DEPLOYMENT_TARGET` which is set to `10.9` if previously empty, unset if previously set to `"clang_default"`, or, otherwise, left as is.
See also issue https://github.com/MDAnalysis/mdanalysis/issues/2180
or PR https://github.com/MDAnalysis/mdanalysis/pull/2184
> overridable env variable MACOSX_DEPLOYMENT_TARGET=10.9

- travis/setup_conda_linux.sh
The current wget generates lots of log lines, like:
```
0K .......... .......... .......... .......... ..........  0% 4.40M 15s
50K .......... .......... .......... .......... ..........  0% 5.27M 14s
100K .......... .......... .......... .......... ..........  0% 13.0M 11s
150K .......... .......... .......... .......... ..........  0% 9.80M 10s
200K .......... .......... .......... .......... ..........  0% 12.9M 9s
250K .......... .......... .......... .......... ..........  0% 27.7M 8s
300K .......... .......... .......... .......... ..........  0% 18.9M 7s
350K .......... .......... .......... .......... ..........  0% 22.0M 7s
400K .......... .......... .......... .......... ..........  0% 23.3M 6s
450K .......... .......... .......... .......... ..........  0% 38.3M 6s
500K …
```
> Reduce the number of wget log lines

- .travis.yml
- travis/setup_dependencies_common.sh
Since #382, builds with `PYTHON_VERSION=3.5` and `NUMPY_VERSION=stable` lead to Python 3.7 being installed because conda-forge doesn't provide a py35 build of numpy 1.16.
This leads either to
* tests with a wrong Python version, or
* build failure if packages without a pip candidate are required.
See also [MDAnalysis Issue #2217](https://github.com/MDAnalysis/mdanalysis/issues/2217).
* Do not change python version if no matching numpy build available, i.e. add `PYTHON_OPTION` to `conda install` call during numpy installation.
* If installing numpy with conda fails, remove `NUMPY_OPTION` from `CONDA_INSTALL` and add it to `PIP_DEPENDENCIES` instead.
I currently don't have a Windows machine around to tinker with the PS script. So, for now, this PR just fixes the issue for Travis.
> pip fallback if numpy build for specified python version is missing

- appveyor/install-miniconda.ps1
On latest `master` on Azure (using AppVeyor scripts) in the last day or so I mysteriously [started getting](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=853):
```
DEBUG:  318+  >>>> pip install --upgrade pip
Collecting pip
Downloading https://files.pythonhosted.org/packages/f9/fb/863012b13912709c13cf5cfdbfb304fa6c727659d6290438e1a88df9d848/pip-19.1-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
Found existing installation: pip 19.0.3
Uninstalling pip-19.0.3:
Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'd:\\a\\1\\s\\conda\\envs\\test\\scripts\\pip.exe'
Consider using the `--user` option or check the permissions.
```
This PR seems to [fix it for us](https://dev.azure.com/mne-tools/mne-python/_build/results?buildI …
> ENH: Add option for no pip upgrade

- .travis.yml
- README.md
- travis/setup_dependencies_common.sh
It hasn't been used for a while and has been archived. We don't really support versions any more that would rely on it.
> Remove astropy-ci-extras

- README.md
- travis/setup_dependencies_common.sh
Covering case when coverage testing triggered with e.g.  command, in e.g. gammapy
> Adding test-cov as a valid coverage trigger

- travis/setup_dependencies_common.sh
Because 3.7.4 causes compilation errors.
xref astropy/astropy#9113 and astropy/astropy#9114
> Pin Python to 3.7.3 on conda

- travis/setup_dependencies_common.sh
Upstream issue has been fixed, and indeed 3.7.4 now works for astropy.
> Remove python 3.7.3 pinning

- .travis.yml
- README.md
- appveyor/install-miniconda.ps1
- test_env.py
- travis/hack_version_numbers.py
- travis/setup_conda.sh
- travis/setup_conda_linux.sh
- travis/setup_conda_osx.sh
- travis/setup_conda_windows.sh
- travis/setup_dependencies_common.sh
We should consider using strict channel priority for all the builds because it can speed up installation considerably. For now I've just replace `true` with `strict`.
I am quite sure some of the appveyor builds are going to break because they use quite old python versions.
> Switch to conda 4.7 as the default conda  and use flexible in place of true

- travis/setup_dependencies_common.sh
This should fix the latest failures on photutils CI (e.g. when we have a new pytest-astropy release, but it doesn't yet propagated through conda)
> pip install astropy-dev build dependencies

- travis/setup_dependencies_common.sh
Closes #427 
This follows the suggestions by @mwcraig to remove the usage of `tee` from `setup_dependencies_common.sh`. I still don't understand why Windows is making the file descriptor read-only for the pipe or what's going on and I'm still worried about this triggering CI time outs from no conda output, but if this makes "best case" Windows builds pass then so be it.
I'll be testing this with my own project and I'll report back later.
> Remove usage of tee to avoid read-only issues on Windows

- test_env.py
- travis/setup_dependencies_common.sh
Neither astropy nor numpy made it to conda defaults yet, but if these are picked up for pip install without issue, I'll go ahead and merge 
(haven't yet updated the LTS version numbers)
> Update the version numbers

- travis/setup_dependencies_common.sh
To close https://github.com/astropy/astropy/issues/9792 and fix the coverage related CI failure in packages using the astropy test runner. 
As it's mentioned in the PR we're not planning to patch over the test runner, given it's being factored out in the next release. If this version limit starts to become burdensome, it can be patched over with an env variable, but I would rather keep it simple for now.
> Limit coverage version number

- travis/setup_dependencies_common.sh
Apparently this second branch wasn't covered with the version pinning causing CI failures in e.g. astropy-helpers.
> Some more coverage version pinning

- travis/setup_dependencies_common.sh
New pytest 5.4 is causing troubles, limiting the version temporarily until a new doctestplus release is done.
> Limiting pytest to be <5.4 temporarily

- .travis.yml
- README.md
- tox.ini
- tox/run_tox.sh
This script installs and run tox, and optionally applies global patches if needed. The idea is to keep this super minimal even in the case where patches need to be applied.
I tried a slightly different approach of leaving it to the caller to actually run the tox command, and using the script to just modify the environment variables, but this didn't work because of issues with quotes in bash, which would require the final tox command to be convoluted.
For now, this script does not do any patching.
I've temporarily disabled all other Travis builds to make sure the one I added works, in case iteration is needed, without wasting CI time.
> Added script that can be used for tox builds

- tox/run_tox.sh
This pins pytest to <5.4 in the tox script. Currently testing this in https://github.com/astropy/astropy/pull/10045
> Pin pytest to <5.4 in tox script

- README.md
- travis/setup_conda.sh
Because `[skip travis]` is natively provided by Travis CI now, as @bsipocz pointed out at astropy/astropy#10186
> MNT: Remove [skip travis]

- appveyor/install-miniconda.ps1
- travis/setup_dependencies_common.sh
To get around CI downstream failing because there is no pyerfa for astropy dev. Also see astropy/astropy#10329
> Install pyerfa for astropy dev

- README.md
- travis/setup_dependencies_common.sh
Close #460 
Mamba is not treated like the `conda` binary where it is copied to all sub-environments. This meant that once we activated our new `test` environment the `mamba` command was no longer available. We have to make sure `mamba` is installed as a dependency in this new environment if we want to use it.
CC @astrofrog who originally wrote #457
> Fix mamba installation to work when installing dependencies

- .travis.yml
- README.md
- test_env.py
- travis/setup_python.sh
Since the core package now uses choco to install Python on Windows and we might want to also avoid conda on MacOS X, I thought it would be handy to make a script that does all the set-up so we can use it across the organization as needed (the CI for the pytest plugins is having the same issues on Windows).
I am testing this out in https://github.com/astropy/astropy/pull/10871
It is quite slow and seems to download half the internet in some form of dependency hell.
It downloads and builds Python from source so is very slow.
This is the easiest way to make sure we don't run into permissions issues and also makes available a ``python`` alias.
I could probably write a small script to try and do this automatically, but didn't want to spend too much time if we don't care.
> Add script to set up Python without conda

- travis/setup_python.sh
Follow-up of #462 - choco was installing the 3.x.0 versions instead of the latest bugfix and the venv creation and activation was broken.
> Install latest bugfix for Windows and fix venv creation and activation
